### ISSUE TITLE
repeated wx.HORIZONTAL

### ISSUE THREAD

**Issue by from1tomax** [necan/wxPython-tutorial#3]
https://github.com/necan/wxPython-tutorial/blob/fbaff7861ebf8a7a40bea1c5a9803dce972d3e1f/4.%E5%B8%83%E5%B1%80.md?plain=1#L113
Maybe the second `wx.HORIZONTAL` should be corrected as `wx.VERTICAL`

**Comment by necan** [comment]
已修改
